<a href="https://colab.research.google.com/github/leonardoub/cmepda/blob/master/BRATS_nested_CV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy

#Load data

In [2]:
#load data from Drive
from google.colab import drive
drive.mount('/gdrive')
#%cd /gdrive

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /gdrive


In [0]:
dataset_path = '/gdrive/My Drive/BRATS/data_without_NAN_with_histologies.csv'

In [0]:
df_data = pd.read_csv(dataset_path)

In [5]:
df_data

Unnamed: 0            ID        Date  ...  TGM_Cog_Z_1    TGM_T_1  Histology
0             0  TCGA-02-0006  1996.08.23  ...     0.052741    2.00000        GBM
1             1  TCGA-02-0009  1997.06.14  ...     0.094336   91.47360        GBM
2             2  TCGA-02-0011  1998.02.01  ...     0.096035  272.42900        GBM
3             3  TCGA-02-0027  1999.03.28  ...     0.096470  128.46800        GBM
4             4  TCGA-02-0033  1997.05.26  ...     0.096894  240.77800        GBM
..          ...           ...         ...  ...          ...        ...        ...
141         141  TCGA-HT-7694  1995.04.04  ...     0.090456  719.23800        LGG
142         142  TCGA-HT-8018  1997.04.11  ...     0.054307    2.00000        LGG
143         143  TCGA-HT-8111  1998.03.30  ...     0.126712    7.06744        LGG
144         144  TCGA-HT-8114  1998.10.30  ...     0.107433   15.52240        LGG
145         145  TCGA-HT-8563  1998.12.09  ...     0.069101    7.62280        LGG

[146 rows x 708 columns]

In [6]:
df_data.columns

Index(['Unnamed: 0', 'ID', 'Date', 'VOLUME_ET', 'VOLUME_NET', 'VOLUME_ED',
       'VOLUME_TC', 'VOLUME_WT', 'VOLUME_BRAIN', 'VOLUME_ET_OVER_NET',
       ...
       'TEXTURE_NGTDM_NET_FLAIR_Busyness',
       'TEXTURE_NGTDM_NET_FLAIR_Complexity',
       'TEXTURE_NGTDM_NET_FLAIR_Strength', 'TGM_p1', 'TGM_dw', 'TGM_Cog_X_1',
       'TGM_Cog_Y_1', 'TGM_Cog_Z_1', 'TGM_T_1', 'Histology'],
      dtype='object', length=708)

In [0]:
data = df_data.drop(['Histology', 'Unnamed: 0', 'ID', 'Date'], axis=1)

In [0]:
labels = df_data.Histology

#Random forest

In [9]:
from sklearn import datasets
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import GridSearchCV 
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV,KFold,cross_val_predict,cross_val_score,StratifiedKFold

from sklearn.svm import SVC
from collections import Counter
from sklearn.metrics import classification_report,accuracy_score

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [0]:
#Vettorizzare i label
encoder = LabelEncoder()
labels_encoded = encoder.fit_transform(labels)

In [0]:
#Scalers
from sklearn.preprocessing import StandardScaler, RobustScaler, MinMaxScaler
scalers_to_test = [StandardScaler(), RobustScaler(), MinMaxScaler(), None]

In [0]:
# Designate distributions to sample hyperparameters from 
n_tree = [10, 50, 100, 150]
n_features_to_test = [0.9]
depth = [10, None]

In [0]:
# Choose cross-validation techniques for the inner and outer loops,
# independently of the dataset.
# E.g "GroupKFold", "LeaveOneOut", "LeaveOneGroupOut", etc.
inner_cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=1)
outer_cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=1)

In [0]:
#RandomForestClassifier
steps = [('scaler', StandardScaler()), ('clf', RandomForestClassifier(random_state=503))]
pipeline = Pipeline(steps)

parameteres = [{'scaler':[StandardScaler()], 
                'clf__n_estimators':list(n_tree), 'clf__criterion':['gini', 'entropy'], 
                'clf__max_depth':depth, 'clf__min_samples_split':[2, 5], 
                'clf__min_samples_leaf':[2, 4], 'clf__class_weight':[None, 'balanced']}]

In [0]:
grid = GridSearchCV(pipeline, param_grid=parameteres, cv=inner_cv, n_jobs=-1, scoring='roc_auc', verbose=1)

In [108]:
# Nested CV with parameter optimization
nested_score = cross_val_score(grid, X=data, y=labels_encoded, cv=outer_cv)


Fitting 3 folds for each of 128 candidates, totalling 384 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.


KeyboardInterrupt: ignored

In questo modo non riesco a sapere quali sono i best HP

In [20]:
nested_score

array([0.81176471, 0.90784314, 0.88865546])

questi dovrebbero essere i risultati del ciclo esterno di CV, ma con quali hp???

#ANOTHER WAY

In [31]:
train_index

array([  0,   1,   3,   4,   5,   6,   7,   8,   9,  10,  11,  13,  14,
        15,  16,  17,  18,  19,  22,  23,  24,  25,  26,  29,  30,  31,
        34,  35,  36,  37,  38,  39,  40,  42,  43,  44,  45,  47,  48,
        49,  50,  52,  53,  54,  57,  58,  59,  61,  63,  65,  66,  68,
        70,  71,  73,  74,  76,  78,  79,  84,  87,  90,  91,  94,  95,
        97,  99, 101, 102, 104, 106, 109, 110, 111, 112, 114, 115, 116,
       117, 118, 120, 121, 122, 125, 127, 128, 129, 130, 131, 132, 133,
       134, 137, 138, 141, 142, 143])

In [0]:
from sklearn.metrics import roc_auc_score

In [0]:
dfObj.iloc[[2 ,0 ] , : ]


In [103]:
train_index

array([  0,   1,   3,   4,   5,   6,   7,   8,   9,  10,  11,  13,  14,
        15,  16,  17,  18,  19,  22,  23,  24,  25,  26,  29,  30,  31,
        34,  35,  36,  37,  38,  39,  40,  42,  43,  44,  45,  47,  48,
        49,  50,  52,  53,  54,  57,  58,  59,  61,  63,  65,  66,  68,
        70,  71,  73,  74,  76,  78,  79,  84,  87,  90,  91,  94,  95,
        97,  99, 101, 102, 104, 106, 109, 110, 111, 112, 114, 115, 116,
       117, 118, 120, 121, 122, 125, 127, 128, 129, 130, 131, 132, 133,
       134, 137, 138, 141, 142, 143])

In [104]:
labels_encoded[train_index]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1])

In [109]:
outer_loop_roc_auc_scores = []
inner_loop_won_params = []
inner_loop_roc_auc_scores = []
D = {}
i = 0

# Looping through the outer loop, feeding each training set into a GSCV as the inner loop
for train_index, test_index in outer_cv.split(data, labels_encoded):
    
    i+=1

    GSCV = GridSearchCV(pipeline, param_grid=parameteres, cv=inner_cv, n_jobs=-1, scoring='roc_auc', verbose=1)
    
    # GSCV is looping through the training data to find the best parameters. This is the inner loop
    GSCV.fit(data.iloc[train_index, :], labels_encoded[train_index])
    
    # The best hyper parameters from GSCV is now being tested on the unseen outer loop test data.
    pred = GSCV.predict(data.iloc[test_index, :])
    

    #conviene far uscire i best_estimators in qualche modo
    #The most important 10 features for the best estimator
    #features_list =  sorted(zip(rank_features, data.columns), reverse=True)[:10]

    #D.update({i : 23})

    # Appending the "winning" hyper parameters and their associated accuracy score
    inner_loop_won_params.append(GSCV.best_params_)
    outer_loop_roc_auc_scores.append(roc_auc_score(labels_encoded[test_index], pred))
    inner_loop_roc_auc_scores.append(GSCV.best_score_)

for i in zip(inner_loop_won_params, outer_loop_roc_auc_scores, inner_loop_roc_auc_scores):
    print(i)

#print('Mean of outer loop accuracy score:' np.mean(outer_loop_roc_auc_scores))

Fitting 3 folds for each of 128 candidates, totalling 384 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed:    6.2s
[Parallel(n_jobs=-1)]: Done 196 tasks      | elapsed:   23.7s
[Parallel(n_jobs=-1)]: Done 384 out of 384 | elapsed:   46.1s finished


Fitting 3 folds for each of 128 candidates, totalling 384 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  88 tasks      | elapsed:    9.5s
[Parallel(n_jobs=-1)]: Done 384 out of 384 | elapsed:   44.5s finished


Fitting 3 folds for each of 128 candidates, totalling 384 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  88 tasks      | elapsed:    9.5s


({'clf__class_weight': 'balanced', 'clf__criterion': 'entropy', 'clf__max_depth': 10, 'clf__min_samples_leaf': 2, 'clf__min_samples_split': 5, 'clf__n_estimators': 150, 'scaler': StandardScaler(copy=True, with_mean=True, with_std=True)}, 0.7852941176470588, 0.9476796955057823)
({'clf__class_weight': None, 'clf__criterion': 'gini', 'clf__max_depth': 10, 'clf__min_samples_leaf': 2, 'clf__min_samples_split': 2, 'clf__n_estimators': 150, 'scaler': StandardScaler(copy=True, with_mean=True, with_std=True)}, 0.9, 0.899026496852584)
({'clf__class_weight': 'balanced', 'clf__criterion': 'gini', 'clf__max_depth': 10, 'clf__min_samples_leaf': 2, 'clf__min_samples_split': 2, 'clf__n_estimators': 100, 'scaler': StandardScaler(copy=True, with_mean=True, with_std=True)}, 0.8550420168067226, 0.9661396574440054)


[Parallel(n_jobs=-1)]: Done 384 out of 384 | elapsed:   44.6s finished


In [110]:
inner_loop_roc_auc_scores

[0.9476796955057823, 0.899026496852584, 0.9661396574440054]

In [111]:
outer_loop_roc_auc_scores

[0.7852941176470588, 0.9, 0.8550420168067226]

In [0]:
rank_features = GSCV.best_estimator_.named_steps["clf"].feature_importances_

In [113]:
rank_features

array([1.18994501e-02, 0.00000000e+00, 0.00000000e+00, 1.40253842e-03,
       0.00000000e+00, 1.00706678e-03, 8.79950020e-03, 1.34298453e-02,
       0.00000000e+00, 1.01936147e-03, 5.50684222e-03, 0.00000000e+00,
       3.40046590e-02, 4.59768202e-03, 1.85830321e-03, 1.98521201e-03,
       1.09124774e-02, 3.40277778e-03, 0.00000000e+00, 1.66962165e-03,
       5.63302809e-04, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 2.41970641e-04, 0.00000000e+00, 5.39639614e-05,
       3.10964476e-03, 8.69565217e-05, 0.00000000e+00, 6.88388284e-04,
       9.41785018e-05, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       7.12597700e-03, 8.85183902e-04, 0.00000000e+00, 9.44034812e-04,
       4.65326605e-03, 9.34753194e-04, 0.00000000e+00, 0.00000000e+00,
       2.45267017e-04, 0.00000000e+00, 9.26519962e-04, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 3.00338666e-03, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.15015208e-03, 0.00000000e+00,
      

In [114]:
 sorted(zip(rank_features, data.columns), reverse=True)[:10]
 #ATTENZIONE HA SENSO SOLO SE NON SI FA PCA

[(0.041318302018261664, 'TEXTURE_NGTDM_ET_T1Gd_Coarseness'),
 (0.03400465904874065, 'VOLUME_ET_OVER_WT'),
 (0.025334093972020345, 'TEXTURE_GLCM_ET_T2_SumAverage'),
 (0.02512868756014921, 'TEXTURE_GLSZM_ET_T1Gd_ZSV'),
 (0.023453617320808272, 'TEXTURE_GLSZM_ET_FLAIR_ZSV'),
 (0.018844483106024136, 'TEXTURE_GLSZM_ET_T2_ZSV'),
 (0.018735550548136387, 'TEXTURE_GLRLM_ET_T2_RLV'),
 (0.01712798594740268, 'TEXTURE_GLRLM_ET_T2_GLN'),
 (0.016689808795072394, 'TEXTURE_GLRLM_ET_T1_GLV'),
 (0.016297975692483625, 'TEXTURE_GLCM_ET_T2_AutoCorrelation')]

Pipeline(memory=None,
         steps=[('scaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('red_dim',
                 PCA(copy=True, iterated_power='auto', n_components=0.9,
                     random_state=42, svd_solver='auto', tol=0.0,
                     whiten=False)),
                ('clf',
                 RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                        class_weight='balanced',
                                        criterion='gini', max_depth=10,
                                        max_features='auto',
                                        max_leaf_nodes=None, max_samples=None,
                                        min_impurity_decrease=0.0,
                                        min_impurity_split=None,
                                        min_samples_leaf=2, min_samples_split=2,
                                        min_weight_fraction_leaf=0.0,
                

In [0]:


df = pd.DataFrame()



for i in range(1, 6):

    #Train test split
    X_train, X_test, y_train, y_test = train_test_split(public_data, public_labels, test_size=0.3, 
    stratify=public_labels, random_state=i*500)

    #Vettorizzare i label
    train_labels_encoded = encoder.fit_transform(y_train)
    test_labels_encoded = encoder.transform(y_test)

    #RandomForestClassifier
    steps = [('scaler', StandardScaler()), ('red_dim', PCA()), ('clf', RandomForestClassifier(random_state=i*503))]

    pipeline = Pipeline(steps)

    parameteres = [{'scaler':scalers_to_test, 'red_dim':[PCA(random_state=42)], 'red_dim__n_components':list(n_features_to_test),
                    'red_dim__whiten':[False, True], 
                    'clf__n_estimators':list(n_tree), 'clf__criterion':['gini', 'entropy'], 
                    'clf__max_depth':depth, 'clf__min_samples_split':[2, 5, 10], 
                    'clf__min_samples_leaf':[1, 2, 4], 'clf__class_weight':[None, 'balanced']}]

    grid = GridSearchCV(pipeline, param_grid=parameteres, cv=3, n_jobs=-1, verbose=1)



     grid.fit(X_train, y_train)

    score_train = grid.score(X_train, y_train)
    score_test = grid.score(X_test, y_test)
    best_p = grid.best_params_

    bp = pd.DataFrame(best_p, index=[i])
    bp['accuracy_train'] = score_train
    bp['accuracy_test'] = score_test
    bp['random_state'] = i*500
    bp['random_state_pca'] = i*42
    bp['random_state_clf'] = i*503

    df = df.append(bp, ignore_index=True)


NameError: ignored

In [0]:
i=1

In [0]:
D={i:0}

In [86]:
D

{1: 0}